from pathlib import Path
from typing import Dict, Any, Optional

class RiffConfig:
    def __init__(self, config_path: Optional[Path] = None) -> None: ...
    @property
    def embedding_model(self) -> str: ...
    @property
    def embedding_dimension(self) -> int: ...
    @property
    def qdrant_endpoint(self) -> str: ...
    @property
    def qdrant_collection(self) -> str: ...
    @property
    def paths(self) -> Dict[str, Path]: ...
    @property
    def venv_location(self) -> Path: ...
    def get(self, key: str, default: Any = None) -> Any: ...

def get_config() -> RiffConfig: ...
def reload_config() -> RiffConfig: ...
def get_embedding_model() -> str: ...
def get_qdrant_endpoint() -> str: ...
def get_paths() -> Dict[str, Path]: ...
